### ISSUE TITLE
How do I get up and running to start contributing

### ISSUE THREAD

**Issue by philipbannon** [GrantBirki/ghtrending#8]
Hey there,

Thanks for creating this project. I'm interested in helping where I can! 

Can you tell me how do i get everything up and running locally and where do I store the data etc.

Many thanks

**Comment by GrantBirki** [comment]
👋 @philipbannon Hi there! Sorry for the slow reply. I'm working on spinning up a better dev env as we speak. The DB actually need to be restructured and I turned it off for a bit to use a better structure. I will add a comment on this issue with some details when things are ready!

**Comment by GrantBirki** [comment]
I should also ask, do you plan on contributing to the front end (React app) or the backend components like the database and the Actions crons which sync events?

**Comment by GrantBirki** [comment]
If you are just looking to do front env development, then it is super easy! Just run these three commands:

- `npm i`
- `npm run prebuild`
- `npm run start`

And 🎉 a local dev instance of the site will start up!
